In [5]:
from joblib import dump, load
import numpy as np

In [6]:
model = load('Dragon_Real_Estate.joblib')

In [7]:
input = np.array([[-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
       -0.23827071, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034]])
model.predict(input)

array([22.45])

In [8]:

input = np.array([[-0.44352175,  3.12628155, -1.35893781, -0.27288841, -1.0542567 ,
        0.50444544, -1.3938808 ,  2.19312325, -0.65766683, -0.78557904,
       -0.69277865,  0.39131918, -0.94116739]])
model.predict(input)

array([25.316])

In [9]:
input = np.array([[ 0.15682292, -0.4898311 ,  0.98336806, -0.27288841,  0.47919371,
        0.29163682,  0.87020968, -0.68730678,  1.63579367,  1.50571521,
        0.81196637,  0.44624347,  0.81480158]])
model.predict(input)

array([16.822])

We can check our model performance by changing the values or by putting different feature value